### ISSUE TITLE
Add in initial code for the connector

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-integration-topic-strimzi#6]

**Comment by planetf1** [comment]
Thanks for submitting the code.

I note there are some security issues reported 

Not had a chance to look yet

See the 'security' tab above and click 'code scanning alerts'

<img width="943" alt="Screenshot 2022-03-21 at 19 22 46" src="https://user-images.githubusercontent.com/7292002/159348671-e8286098-d7ba-47b0-b07b-e387fb981261.png">

**Comment by davidradl** [comment]
@planetf1 I have fixed them
